### ISSUE TITLE
Use LatLng from latlong2 instead of PolylinePoint

### ISSUE THREAD

**Issue by JFtechOfficial** [ahmedsaleh210/georouter#1]
the [latlong2 package](https://pub.dev/packages/latlong2) is well maintained and it's widely used for latitude-longitude representation. The usage of latlong2 would allow inter-compatibility with other packages like [flutter_map](https://pub.dev/packages/flutter_map).

**Comment by ahmedsaleh210** [comment]
Thank you for highlighting the benefits of latlong2. It's a well-maintained and widely used package for representing latitude and longitude coordinates. Interoperability with other packages like flutter_map is definitely a valuable consideration.

However, I'd like to raise awareness of a potential conflict with the latlng class included in the core google_maps_flutter package used for Google Maps integration in Flutter. Both packages define a class named LatLng, which could lead to confusion and errors for developers who use both latlong2 and google_maps_flutter in their projects.
